config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  
  resources :registered_apps
  
  authenticated :user do
    root 'registered_apps#index', as: :authenticated_root
  end
  
  get 'welcome/index'
  get 'welcome/about'
  
  root 'welcome#index'
  
  namespace :api, default: { format: :json } do
    match '/events', to: 'events#preflight', via: [:options]
    resources :events, only: [:create]
  end
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :registered_app
end

app/models/registered_app.rb
class RegisteredApp < ActiveRecord::Base
  belongs_to :user
  has_many :events
  validates :url, url: true, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
  
  has_many :registered_apps
end

app/controllers/api/events_controller.rb
class API::EventsController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :set_access_control_headers
  
  def set_access_control_headers
    headers['Access-Control-Allow-Origin'] = '*'
    headers['Access-Control-Allow-Methods'] = 'POST, GET, OPTIONS'
    headers['Access-Control-Allow-Headers'] = 'Content-Type'
  end
  
  def create
    registered_app = RegisteredApp.find_by(url: request.env['HTTP_ORIGIN'])

    unless registered_app
      render json: "Unregistered Application", status: :unprocessable_entity
    end

    @event = registered_app.events.new(event_params)
    if @event.save
      render json: @event, status: :created
    else
      render json: {errors: @event.errors}, status: :unprocessable_entity
    end
  end
  
  def preflight
    head 200
  end
  
  private
  
  def event_params
    params.require(:event).permit(:name)
  end
end

app/controllers/api/events_controller_controller.rb
class API::EventsControllerController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_filter :set_access_control_headers
  
  def set_access_control_headers
    headers['Access-Control-Allow-Origin'] = '*'
    headers['Access-Control-Allow-Method'] = 'POST, GET, OPTIONS'
    headers['Access-Control-Allow-Headers'] = 'Content-Type'
  end
  
  def create
    registered_app = RegisteredApp.find_by(url: request.env['HTTP_ORIGIN'])

    unless registered_app
      render json: "Unregistered Application", status: :unprocessable_entity
    end

    @event = registered_app.events.new(event_params)
    if @event.save
      render json: @event, status: :created
    else
      render json: {errors: @event.errors}, status: :unprocessable_entity
    end
  end
  
  def preflight
    head 200
  end
  
  private
  
  def event_params
    params.require(:event).permit(:name)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/registered_apps_controller.rb
class RegisteredAppsController < ApplicationController
  def index
    @registered_apps = current_user.registered_apps
  end

  def new
    @registered_app = RegisteredApp.new
  end

  def create
    @registered_app = current_user.registered_apps.new(app_params)
    
    if @registered_app.save
      redirect_to @registered_app, notice: "Your app has been registered!"
    else
      flash[:alert] = "There was an error saving your app!"
      render :new
    end
  end

  def show
    @registered_app = current_user.registered_apps.find(params[:id])
    @events = @registered_app.events.group_by(&:name)
  end

  def edit
    @registered_app = RegisteredApp.find(params[:id])
  end

  def update
    @registered_app = RegisteredApp.find(params[:id])
    @registered_app.assign_attributes(app_params)
    
    if @registered_app.save
      redirect_to @registered_app, notice: "Your changes have been saved!"
    else
      flash[:alert] = "There was an error saving your changes, please try again"
      render :edit
    end
  end

  def app_params
    params.require(:registered_app).permit(:name, :url)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/api/events_controller_helper.rb
module API::EventsControllerHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for flash_type
    { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }[flash_type.to_sym] || flash_type.to_s
  end
  
  def flash_messages(opt = {})
    flash.each do |message_type, message|
      concat(
        content_tag(:div, message, class: "alert #{bootstrap_class_for(message_type)} fade in") do
          concat content_tag(:button, 'x', class: "close", data: { dismiss: 'alert' })
          concat message
        end
      )
    end
    nil
  end
end

app/helpers/events_controller/api_helper.rb
module EventsController::APIHelper
end

app/helpers/registered_apps_helper.rb
module RegisteredAppsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocmetrics</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class='navbar navbar-toggleable-md navbar-inverse bg-primary'>
  <div class='collapse navbar-collapse'>
    <div class='navbar-nav box'>
      <%= link_to "Blocmetrics", root_path, class: 'navbar-brand' %>
      <ul class='nav navbar-nav pull-right'>
        <% if current_user %>
          <li>
            <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: 'nav-item nav-link' %>
          </li>
        <% else %>
          <li>
            <%= link_to "Sign In", new_user_session_path, class: 'nav-item nav-link' %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

<%= flash_messages %>

<%= yield %>
</body>
</html>

app/views/registered_apps/_form.html.erb
<div class="col-md-6">
  <%= form_for @registered_app do |a| %>
  <div class="form-group">
    <%= a.label :name %>
    <%= a.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= a.label :url %>
    <%= a.text_field :url, class: "form-control" %>
  </div>
  <div class="btn-group">
    <%= a.submit "Save", class: "btn" %>
    <%= link_to "Cancel", root_path, class: "btn btn-danger" %>
  </div>
  <% end %>
</div>

app/views/registered_apps/edit.html.erb
<div class='col-md-offset-4'>
  <%= render 'form' %>
</div>

app/views/registered_apps/index.html.erb
<div class='container'>
  <div class='list-group'>
    <button><%= link_to "New Application", new_registered_app_path %></button>
      <% @registered_apps.each do |app| %>
          <%= link_to "Application: #{app.name}", app, class: 'list-group-item list-group-item-action' %>
        <div class='app-link-group'>
          <%= link_to "Go to this app", app.url, class: 'app-link' %> <span class='glyphicon glyphicon-arrow-right'></span>
        </div>
      <% end %>
  </div>
</div>

app/views/registered_apps/new.html.erb
<div class='col-md-offset-4'>
  <%= render 'form' %>
</div>

app/views/registered_apps/show.html.erb
<div class='col-md-12'>
  <h2>
    <%= @registered_app.name %> - <%= link_to @registered_app.url %>
    <div class='pull-right'>
      <%= link_to "Edit", edit_registered_app_path %>
      <%= link_to "Delete", "#" %>
    </div>
  </h2>
  <div>
    <h3>Analytics</h3>
    <% if @registered_app.events.any? %>
        <div class='col-md-6'>
          <h4>Events:</h4>
          <%= pie_chart @registered_app.events.group(:name).count %>
        </div>
        <div class='col-md-6'>
          <h4>Events over time:</h4>
          <%= line_chart @registered_app.events.group_by_day(:created_at).count %>
        </div>
    <% else %>
      <div class='jumbotron'>
        <div class='col-md-6'>
          <h4>No information yet!</h4>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<%= @user.name %>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/index.html.erb
<div class='container container-full'>
<div class='col-md-8 col-md-offset-2'>
  <div id='welcome' class='carousel slide welcome-carousel' data-ride='carousel' data-interval=''>
    <ol class='carousel-indicators bg-inverse'>
      <li data-target='#welcome' data-slide-to='0' class='active'></li>
      <li data-target='#welcome' data-slide-to='1'></li>
    </ol>
    <div class='carousel-inner center' role='listbox'>
      <div class='item active'>
        <h1>Welcome to Blocmetrics!</h1>
        <h3>New user?</h3>
        <p><%= link_to "Sign up", new_user_registration_path %> today!</p>
      </div>
      <div class='item'>
        <span class='glyphicon glyphicon-stats d-block img-fluid'></span>
        <h3 class='description'>Use Blocmetrics to help you keep statistics on your applications!</h3>
      </div>
    </div>
    <a class='carousel-control-left' href='#welcome' role='button' data-slide='prev'>
      <span class='glyphicon glyphicon-chevron-left'></span>
    </a>
    <a class='carousel-control-right' href='#welcome' role='button' data-slide='next'>
      <span class='glyphicon glyphicon-chevron-right'></span>
    </a>
  </div>
</div>
</div>